namespace FilterableHarvestTool {
    public static class FilterableHarvestToolStrings {
        public const string FILTERABLEHARVESTTOOL_WILD_ENABLEHARVEST = "STRINGS.UI.TOOLS.FILTERLAYERS.ENABLEHARVEST_WILD";
        public const string FILTERABLEHARVESTTOOL_WILD_DISABLEHARVEST = "STRINGS.UI.TOOLS.FILTERLAYERS.DISABLEHARVEST_WILD";

        public const string FILTERABLEHARVESTTOOL_FARM_ENABLEHARVEST = "STRINGS.UI.TOOLS.FILTERLAYERS.ENABLEHARVEST_FARM";
        public const string FILTERABLEHARVESTTOOL_FARM_DISABLEHARVEST = "STRINGS.UI.TOOLS.FILTERLAYERS.DISABLEHARVEST_FARM";
    }
}
